# -------------------------------------------------------------------------------
#  PROJECT: Zybo Base
# -------------------------------------------------------------------------------
#  AUTHORS: Pavel Benacek <pavel.benacek@gmail.com>
#  LICENSE: The MIT License (MIT), please read LICENSE file
#  WEBSITE: https://github.com/benycze/zybo-base
# -------------------------------------------------------------------------------

obj-$(CONFIG_LED_MODULE)		+= led-module/
obj-$(CONFIG_RGB_LED_MODULE)	+= rgb-led-module/
obj-$(CONFIG_SWITCH_MODULE)		+= switch-module/